name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWU3Y2ZjMDgtMGZhOC00NzYyLTg2MjMtNThmMzI2YTUzM2QwIiwidGVuYW50X2lkIjoiZWM3NThmMzczNGRjYTM0MTYyMzVmMDhmM2UwNWMxMjQyYWRmMDA1MDE0NWM2MzJiZjIwOWQ1NDdlMWE5MzE3MSIsImludGVybmFsX3NlY3JldCI6ImYzOGNlMDQyLTQyMjgtNDQyMC05NzI3LTY2OTk0NDk1ZDQ2OSJ9.IVDzPOUMn28nK-7QHpkJPr3njwZFgUsPhOCq6CtkGK8"
JWT_SECRET = "secret"

